/**
 * FAQ - English
 *
 * 格式: [id, question, answer]
 * 一行一个问答，更易于编辑
 */

import { FAQData } from '../types';

// 问答列表 - 每行一个 [id, 问题, 答案]
const items: [string, string, string][] = [
  [
    'whatIsVoicica',
    'What is Voicica AI about and What Services does it Provide?',
    'Voicica AI is a platform focused on AI voiceover tools, such as text-to-speech and voice cloning, as well as AI music-related products, including AI music generator.',
  ],
  [
    'isFree',
    'Is Voicica AI Free?',
    'Yes, our tools like text-to-speech, voice cloning, AI music generator and AI song cover, all have free trial versions available. Besides, we provide a free toolbox with various online tools for users to try out.',
  ],
  [
    'howToUse',
    'How Can I Use AI Voice Generator on Voicica AI?',
    'Using the AI voice generator on Voicica AI is quite simple: Method 1: Go to the dashboard of Voicica AI text to speech, select an AI voice, input text and then click \'Audition\'. Method 2: Go to the dashboard of Voicica AI voice cloning, choose the way of cloning, upload audio or enter the parameters, finally start cloning.',
  ],
  [
    'bestGenerator',
    'What is the Best AI Voice Generator?',
    'Voicica AI text to speech is one of the best AI voice generators, offering a wide range of realistic voices for text-to-speech and voice cloning. It supports multiple languages and editting features, making it ideal for content creators, video producers, and anyone needing high-quality voiceovers.',
  ],
  [
    'languages',
    'What Languages does Your Text to Speech Tool Support?',
    'Voicica AI text to speech now supports over 190 languages and accents, including English, Spanish, French, German, Italian, Portuguese, Dutch, Russian, Vietnamese, Swedish, Finnish, Arabic, Estonian, Filipino, Greek, Korean, Lao, Hindi, Croatian, Cantonese, Danish, Japanese, Indonesian, Irish, Polish, Romanian and so on.',
  ],
  [
    'howTtsWorks',
    'How does text to speech work?',
    'Text-to-speech (TTS) technology works by analyzing written text, converting it into phonetic representations, and synthesizing speech output with appropriate prosody and intonation. The system interprets linguistic elements such as grammar and syntax to ensure accurate speech synthesis. Depending on the context and punctuation, TTS determines factors like emphasis, pitch, rhythm, and pause placement to enhance the naturalness of the spoken content. Finally, the synthesized speech is outputted through audio devices, allowing users to listen to the spoken text.',
  ],
  [
    'useCases',
    'What Kind of Industries or Use Cases Can Benefit from Voicica AI Text to Speech?',
    'Voicica AI is versatile and benefits a wide range of industries and use cases, including content creation, e-learning, entertainment, media and marketing and others.',
  ],
  [
    'quality',
    'Is the Generated Speech Output High-quality and Natural-sounding?',
    'Yes, the speech output generated by Voicica AI is high-quality and natural-sounding. It uses advanced AI technology to create realistic voices with accurate intonation, pacing, and expression.',
  ],
];

export const faqData: FAQData = {
  title: 'Frequently Asked Questions about Voicica AI',
  description: 'Find answers to common questions about our AI voice generation platform.',
  items: items.map(([id, question, answer]) => ({ id, question, answer })),
};